import { EmailAnalysisResult } from "../types";
import { motion, AnimatePresence } from "motion/react";
import { ShieldCheck, ShieldAlert, Shield, AlertTriangle, Info, BookOpen, Target, ChevronDown } from "lucide-react";
import { useState } from "react";
import SuspiciousTextHighlighter from "./SuspiciousTextHighlighter";
import EmailStatistics from "./EmailStatistics";
import LinkAnalysis from "./LinkAnalysis";
import SenderAnalysis from "./SenderAnalysis";
import ThreatTimeline from "./ThreatTimeline";

interface Props {
  result: EmailAnalysisResult;
  emailText: string;
}

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.1 }
  }
};

const item = {
  hidden: { y: 20, opacity: 0 },
  show: { y: 0, opacity: 1 }
};

const CircularProgress = ({ value, color }: { value: number, color: string }) => {
  const radius = 40;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (value / 100) * circumference;

  return (
    <div className="relative w-24 h-24">
      <svg className="w-full h-full -rotate-90">
        <circle cx="48" cy="48" r={radius} className="text-gray-800" strokeWidth="8" fill="transparent" stroke="currentColor" />
        <motion.circle
          initial={{ strokeDashoffset: circumference }}
          animate={{ strokeDashoffset }}
          transition={{ duration: 1, ease: "easeOut" }}
          cx="48" cy="48" r={radius} className={`text-${color}-500`} strokeWidth="8" fill="transparent" stroke="currentColor" strokeDasharray={circumference} strokeLinecap="round"
        />
      </svg>
      <div className="absolute inset-0 flex items-center justify-center font-bold text-xl">{value}%</div>
    </div>
  );
};

export default function EmailAnalysisResultView({ result, emailText }: Props) {
  const [isEducationOpen, setIsEducationOpen] = useState(false);
  const isSafe = result.verdict.toLowerCase().includes("safe");
  const isSuspicious = result.verdict.toLowerCase().includes("suspicious");

  const getVerdictTheme = () => {
    if (isSafe) return { color: "emerald", icon: ShieldCheck, label: "Safe" };
    if (isSuspicious) return { color: "amber", icon: ShieldAlert, label: "Suspicious" };
    return { color: "rose", icon: Shield, label: "Likely Scam" };
  };

  const theme = getVerdictTheme();
  const colorClass = `text-${theme.color}-500`;
  const bgClass = `bg-${theme.color}-500/10`;
  const borderClass = `border-${theme.color}-500/20`;

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-8 mt-12" aria-live="polite">
      <div className="border-b border-gray-800 pb-6">
        <h2 className="text-3xl font-bold text-white">Security Analysis Report</h2>
        <p className="text-gray-400">Generated by ScamShield AI</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <motion.div variants={item} className={`p-8 rounded-3xl border ${borderClass} ${bgClass} flex flex-col items-center justify-center gap-3`}>
          <theme.icon className={`w-12 h-12 ${colorClass}`} />
          <h3 className="text-2xl font-bold">{theme.label}</h3>
        </motion.div>

        <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl flex flex-col items-center justify-center gap-2">
          <span className="text-gray-400 font-medium">Confidence</span>
          <CircularProgress value={result.confidence} color={theme.color} />
        </motion.div>

        <motion.div variants={item} className="grid grid-rows-2 gap-4">
          <div className="bg-gray-950/60 border border-gray-800 p-4 rounded-2xl flex items-center justify-center gap-2 font-semibold">
            Risk: <span className={`px-3 py-1 rounded-full text-sm bg-${theme.color}-500/20 ${colorClass}`}>{result.riskLevel}</span>
          </div>
          <div className="bg-gray-950/60 border border-gray-800 p-4 rounded-2xl flex items-center justify-center gap-2 font-semibold">
            Threat: <span className="text-cyan-400">{result.threatType}</span>
          </div>
        </motion.div>
      </div>

      <motion.div variants={item}>
        <ThreatTimeline />
      </motion.div>

      <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
        <SenderAnalysis text={emailText} />
      </motion.div>

      <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
        <h4 className="text-xl font-semibold text-white mb-6">Email Statistics</h4>
        <EmailStatistics text={emailText} />
      </motion.div>

      <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
        <h4 className="text-xl font-semibold text-white mb-6">Link Analysis</h4>
        <LinkAnalysis text={emailText} />
      </motion.div>

      <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
        <p className="text-gray-200 text-lg leading-relaxed mb-6">{result.summary}</p>
        <h4 className="text-xl font-semibold text-white mb-4">Detected Suspicious Content</h4>
        <SuspiciousTextHighlighter emailText={emailText} detectedPhrases={result.detectedPhrases} />
      </motion.div>

      <div className="grid md:grid-cols-2 gap-6">
        <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
          <h4 className="text-xl font-semibold text-white mb-6 flex items-center gap-3">
            <AlertTriangle className="text-rose-500 w-6 h-6" /> Red Flags
          </h4>
          {result.redFlags.length > 0 ? (
            <ul className="space-y-3">
              {result.redFlags.map((flag, i) => (
                <li key={i} className="flex items-center gap-3 bg-gray-900/50 p-4 rounded-xl border border-gray-800 hover:border-rose-500/30 transition-colors">
                  <span className="w-2 h-2 rounded-full bg-rose-500" />
                  <span className="text-gray-200">{flag}</span>
                </li>
              ))}
            </ul>
          ) : <p className="text-emerald-500 font-medium">✓ No major red flags detected.</p>}
        </motion.div>

        <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
          <h4 className="text-xl font-semibold text-white mb-6 flex items-center gap-3">
            <ShieldCheck className="text-emerald-500 w-6 h-6" /> Safe Indicators
          </h4>
          <ul className="space-y-3">
            {result.safeIndicators.map((indicator, i) => (
              <li key={i} className="flex items-center gap-3 bg-gray-900/50 p-4 rounded-xl border border-gray-800 hover:border-emerald-500/30 transition-colors">
                <span className="w-2 h-2 rounded-full bg-emerald-500" />
                <span className="text-gray-200">{indicator}</span>
              </li>
            ))}
          </ul>
        </motion.div>
      </div>

      <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 p-8 rounded-3xl">
        <h4 className="text-xl font-semibold text-white mb-6 flex items-center gap-3">
          <ShieldAlert className="text-cyan-500 w-6 h-6" /> Recommendations
        </h4>
        <ul className="grid md:grid-cols-2 gap-4">
          {result.recommendations.map((rec, i) => (
            <li key={i} className="flex gap-4 p-4 rounded-xl border border-gray-800 hover:bg-gray-900/50 transition-colors">
              <span className="text-cyan-500 font-bold">0{i + 1}.</span>
              <span className="text-gray-200">{rec}</span>
            </li>
          ))}
        </ul>
      </motion.div>

      <motion.div variants={item} className="bg-gray-950/60 border border-gray-800 rounded-3xl overflow-hidden">
        <button 
          onClick={() => setIsEducationOpen(!isEducationOpen)}
          className="w-full p-8 flex items-center justify-between text-left hover:bg-gray-900/50 transition-colors"
        >
          <h4 className="text-xl font-semibold text-white flex items-center gap-3">
            <BookOpen className="text-purple-500 w-6 h-6" /> Why This Matters
          </h4>
          <ChevronDown className={`w-6 h-6 text-gray-400 transition-transform ${isEducationOpen ? 'rotate-180' : ''}`} />
        </button>
        <AnimatePresence>
          {isEducationOpen && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="px-8 pb-8 text-gray-200 text-lg leading-relaxed"
            >
              <div className="bg-gray-900/50 p-6 rounded-2xl border border-gray-800">
                {result.education}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </motion.div>
  );
}
